spring.application.name=EcommerceApp
server.port = 8080


#spring.datasource.url=jdbc:mysql://localhost/test
#spring.datasource.username=root
#spring.datasource.password=secret
#spring,jpa.hibernate.ddl-auto=update

## Example IN Command line

##   --server.port=7070

